// Automatically generated by `BlobVariantFieldCodeGenerator`
namespace EntitiesBT.Variant
{

public interface SingleWriterVariant : EntitiesBT.Variant.IVariantWriter<System.Single> { }
public class SingleNodeVariantWriter : EntitiesBT.Variant.NodeVariant.Writer<System.Single>, SingleWriterVariant { }
public class SingleComponentVariantWriter : EntitiesBT.Variant.ComponentVariant.Writer<System.Single>, SingleWriterVariant { }


}

