// Automatically generated by `BlobVariantFieldCodeGenerator`

using System;
using EntitiesBT.Attributes;
using UnityEngine;

namespace EntitiesBT.Variant
{

public interface SingleReaderAndWriterVariant : EntitiesBT.Variant.IVariantReaderAndWriter<System.Single> { }
public class SingleNodeVariantReaderAndWriter : EntitiesBT.Variant.NodeVariant.ReaderAndWriter<System.Single>, SingleReaderAndWriterVariant { }
public class SingleComponentVariantReaderAndWriter : EntitiesBT.Variant.ComponentVariant.ReaderAndWriter<System.Single>, SingleReaderAndWriterVariant { }
public class SingleLocalVariantReaderAndWriter : EntitiesBT.Variant.LocalVariant.ReaderAndWriter<System.Single>, SingleReaderAndWriterVariant { }

[Serializable]
public class SingleSerializedReaderAndWriterVariant
{
    public bool IsLinked = true;

    [SerializeReference]
    [MultiProperty]
    [DisableIf(nameof(IsLinked), false)]
    [SerializeReferenceButton]
    public SingleReaderAndWriterVariant ReaderAndWriter;

    [SerializeReference]
    [MultiProperty]
    [DisableIf(nameof(IsLinked))]
    [SerializeReferenceButton]
    public SingleReaderVariant Reader;

    [SerializeReference]
    [MultiProperty]
    [DisableIf(nameof(IsLinked))]
    [SerializeReferenceButton]
    public SingleWriterVariant Writer;
}

}

