// Automatically generated by `BlobVariantFieldCodeGenerator`
namespace EntitiesBT.Variant
{

public interface SingleReaderAndWriterVariant : EntitiesBT.Variant.IVariantReaderAndWriter<System.Single> { }
public class SingleNodeVariantReaderAndWriter : EntitiesBT.Variant.NodeVariant.ReaderAndWriter<System.Single>, SingleReaderAndWriterVariant { }
public class SingleComponentVariantReaderAndWriter : EntitiesBT.Variant.ComponentVariant.ReaderAndWriter<System.Single>, SingleReaderAndWriterVariant { }
public class SingleLocalVariantReaderAndWriter : EntitiesBT.Variant.LocalVariant.ReaderAndWriter<System.Single>, SingleReaderAndWriterVariant { }


}

