// Automatically generated by `BlobVariantFieldCodeGenerator`
namespace EntitiesBT.Variant
{

public interface SingleVariantReaderAndWriter : EntitiesBT.Variant.IVariantReaderAndWriter<System.Single> { }
public class SingleNodeVariantReaderAndWriter : EntitiesBT.Variant.NodeVariant.ReaderAndWriter<System.Single>, SingleVariantReaderAndWriter { }
public class SingleComponentVariantReaderAndWriter : EntitiesBT.Variant.ComponentVariant.ReaderAndWriter<System.Single>, SingleVariantReaderAndWriter { }
public class SingleLocalVariantReaderAndWriter : EntitiesBT.Variant.LocalVariant.ReaderAndWriter<System.Single>, SingleVariantReaderAndWriter { }


[System.Serializable]
public class SingleSerializedReaderAndWriterVariant : EntitiesBT.Variant.ISerializedVariantReaderAndWriter<System.Single>
{
    [UnityEngine.SerializeField]
    private bool _isLinked = true;
    public bool IsLinked => _isLinked;

    [UnityEngine.SerializeReference]
    [EntitiesBT.Attributes.HideIf(nameof(_isLinked), false)]
    [EntitiesBT.Attributes.SerializeReferenceDrawer]
    private SingleVariantReaderAndWriter _readerAndWriter;
    public EntitiesBT.Variant.IVariantReaderAndWriter<System.Single> ReaderAndWriter => _readerAndWriter;

    [UnityEngine.SerializeReference]
    [EntitiesBT.Attributes.HideIf(nameof(_isLinked))]
    [EntitiesBT.Attributes.SerializeReferenceDrawer]
    private SingleVariantReader _reader;
    public EntitiesBT.Variant.IVariantReader<System.Single> Reader => _reader;

    [UnityEngine.SerializeReference]
    [EntitiesBT.Attributes.HideIf(nameof(_isLinked))]
    [EntitiesBT.Attributes.SerializeReferenceDrawer]
    private SingleVariantWriter _writer;
    public EntitiesBT.Variant.IVariantWriter<System.Single> Writer => _writer;
}

}

