// Automatically generated by `BlobVariantFieldCodeGenerator`
namespace EntitiesBT.Variant
{

public interface SingleVariantWriter : EntitiesBT.Variant.IVariantWriter<System.Single> { }
public class SingleNodeVariantWriter : EntitiesBT.Variant.NodeVariant.Writer<System.Single>, SingleVariantWriter { }
public class SingleComponentVariantWriter : EntitiesBT.Variant.ComponentVariant.Writer<System.Single>, SingleVariantWriter { }


}

