// Automatically generated by `BlobVariantFieldCodeGenerator`
namespace EntitiesBT.Variant
{

public interface SingleReaderVariant : EntitiesBT.Variant.IVariantReader<System.Single> { }
public class SingleLocalVariantReader : EntitiesBT.Variant.LocalVariant.Reader<System.Single>, SingleReaderVariant { }
public class SingleComponentVariantReader : EntitiesBT.Variant.ComponentVariant.Reader<System.Single>, SingleReaderVariant { }
public class SingleNodeVariantReader : EntitiesBT.Variant.NodeVariant.Reader<System.Single>, SingleReaderVariant { }
public class SingleScriptableObjectVariantReader : EntitiesBT.Variant.ScriptableObjectVariant.Reader<System.Single>, SingleReaderVariant { }

public interface SingleWriterVariant : EntitiesBT.Variant.IVariantReader<System.Single> { }
// public class SingleLocalVariantWriter : EntitiesBT.Variant.LocalVariant.Writer<System.Single>, SingleWriterVariant { }
public class SingleComponentVariantWriter : EntitiesBT.Variant.ComponentVariant.Writer<System.Single>, SingleWriterVariant { }
public class SingleNodeVariantWriter : EntitiesBT.Variant.NodeVariant.Writer<System.Single>, SingleWriterVariant { }

}

