// Automatically generated by `BlobVariantFieldCodeGenerator`

using System;
using UnityEngine;

namespace EntitiesBT.Variant
{

public interface SingleReaderAndWriterVariant : EntitiesBT.Variant.IVariantReaderAndWriter<System.Single> { }
public class SingleNodeVariantReaderAndWriter : EntitiesBT.Variant.NodeVariant.ReaderAndWriter<System.Single>, SingleReaderAndWriterVariant { }
public class SingleComponentVariantReaderAndWriter : EntitiesBT.Variant.ComponentVariant.ReaderAndWriter<System.Single>, SingleReaderAndWriterVariant { }
public class SingleLocalVariantReaderAndWriter : EntitiesBT.Variant.LocalVariant.ReaderAndWriter<System.Single>, SingleReaderAndWriterVariant { }

[Serializable]
public class SingleSerializedReaderAndWriterVariant : ISerializedReaderAndWriter<System.Single>
{
    [SerializeField] private bool _isLinked = true;
    public bool IsLinked => _isLinked;

    [UnityEngine.SerializeReference, SerializeReferenceButton] private SingleReaderAndWriterVariant _readerAndWriter;
    public IVariantReaderAndWriter<System.Single> ReaderAndWriter => _readerAndWriter;

    [UnityEngine.SerializeReference, SerializeReferenceButton] private SingleReaderVariant _reader;
    public IVariantReader<System.Single> Reader => _reader;

    [UnityEngine.SerializeReference, SerializeReferenceButton] private SingleWriterVariant _writer;
    public IVariantWriter<System.Single> Writer => _writer;
}

}

