// Automatically generated by `BlobVariantFieldCodeGenerator`
namespace EntitiesBT.Variant
{

public interface SingleVariantReader : EntitiesBT.Variant.IVariantReader<System.Single> { }
public class SingleNodeVariantReader : EntitiesBT.Variant.NodeVariant.Reader<System.Single>, SingleVariantReader { }
public class SingleComponentVariantReader : EntitiesBT.Variant.ComponentVariant.Reader<System.Single>, SingleVariantReader { }
public class SingleLocalVariantReader : EntitiesBT.Variant.LocalVariant.Reader<System.Single>, SingleVariantReader { }
public class SingleScriptableObjectVariantReader : EntitiesBT.Variant.ScriptableObjectVariant.Reader<System.Single>, SingleVariantReader { }


}

