// Automatically generated by `BlobVariableFieldCodeGenerator`
namespace EntitiesBT.Variable
{

public interface SingleProperty : EntitiesBT.Variable.IVariableProperty<System.Single> { }
public class SingleCustomVariableProperty : EntitiesBT.Variable.CustomVariableProperty<System.Single>, SingleProperty { }
public class SingleComponentVariableProperty : EntitiesBT.Variable.ComponentVariableProperty<System.Single>, SingleProperty { }
public class SingleNodeVariableProperty : EntitiesBT.Variable.NodeVariableProperty<System.Single>, SingleProperty { }

}

