using EntitiesBT.Variant.Expression;
using Unity.Mathematics;

[assembly: ExpressionType(typeof(byte), 0)]
[assembly: ExpressionType(typeof(short), 1)]
[assembly: ExpressionType(typeof(int), 2)]
[assembly: ExpressionType(typeof(long), 3)]

[assembly: ExpressionType(typeof(sbyte), 4)]
[assembly: ExpressionType(typeof(ushort), 5)]
[assembly: ExpressionType(typeof(uint), 6)]
[assembly: ExpressionType(typeof(ulong), 7)]

[assembly: ExpressionType(typeof(float), 8)]
[assembly: ExpressionType(typeof(double), 9)]

[assembly: ExpressionType(typeof(bool), 10)]

[assembly: ExpressionType(typeof(bool2), 20)]
[assembly: ExpressionType(typeof(bool2x2), 21)]
[assembly: ExpressionType(typeof(bool2x3), 22)]
[assembly: ExpressionType(typeof(bool2x4), 23)]
[assembly: ExpressionType(typeof(bool3), 24)]
[assembly: ExpressionType(typeof(bool3x2), 25)]
[assembly: ExpressionType(typeof(bool3x3), 26)]
[assembly: ExpressionType(typeof(bool3x4), 27)]
[assembly: ExpressionType(typeof(bool4), 28)]
[assembly: ExpressionType(typeof(bool4x2), 29)]
[assembly: ExpressionType(typeof(bool4x3), 30)]
[assembly: ExpressionType(typeof(bool4x4), 31)]

[assembly: ExpressionType(typeof(int2), 32)]
[assembly: ExpressionType(typeof(int2x2), 33)]
[assembly: ExpressionType(typeof(int2x3), 34)]
[assembly: ExpressionType(typeof(int2x4), 35)]
[assembly: ExpressionType(typeof(int3), 36)]
[assembly: ExpressionType(typeof(int3x2), 37)]
[assembly: ExpressionType(typeof(int3x3), 38)]
[assembly: ExpressionType(typeof(int3x4), 39)]
[assembly: ExpressionType(typeof(int4), 40)]
[assembly: ExpressionType(typeof(int4x2), 41)]
[assembly: ExpressionType(typeof(int4x3), 42)]
[assembly: ExpressionType(typeof(int4x4), 43)]

[assembly: ExpressionType(typeof(uint2), 44)]
[assembly: ExpressionType(typeof(uint2x2), 45)]
[assembly: ExpressionType(typeof(uint2x3), 46)]
[assembly: ExpressionType(typeof(uint2x4), 47)]
[assembly: ExpressionType(typeof(uint3), 48)]
[assembly: ExpressionType(typeof(uint3x2), 49)]
[assembly: ExpressionType(typeof(uint3x3), 50)]
[assembly: ExpressionType(typeof(uint3x4), 51)]
[assembly: ExpressionType(typeof(uint4), 52)]
[assembly: ExpressionType(typeof(uint4x2), 53)]
[assembly: ExpressionType(typeof(uint4x3), 54)]
[assembly: ExpressionType(typeof(uint4x4), 55)]

[assembly: ExpressionType(typeof(float2), 56)]
[assembly: ExpressionType(typeof(float2x2), 57)]
[assembly: ExpressionType(typeof(float2x3), 58)]
[assembly: ExpressionType(typeof(float2x4), 59)]
[assembly: ExpressionType(typeof(float3), 60)]
[assembly: ExpressionType(typeof(float3x2), 61)]
[assembly: ExpressionType(typeof(float3x3), 62)]
[assembly: ExpressionType(typeof(float3x4), 63)]
[assembly: ExpressionType(typeof(float4), 64)]
[assembly: ExpressionType(typeof(float4x2), 65)]
[assembly: ExpressionType(typeof(float4x3), 66)]
[assembly: ExpressionType(typeof(float4x4), 67)]

[assembly: ExpressionType(typeof(double2), 68)]
[assembly: ExpressionType(typeof(double2x2), 69)]
[assembly: ExpressionType(typeof(double2x3), 70)]
[assembly: ExpressionType(typeof(double2x4), 71)]
[assembly: ExpressionType(typeof(double3), 72)]
[assembly: ExpressionType(typeof(double3x2), 73)]
[assembly: ExpressionType(typeof(double3x3), 74)]
[assembly: ExpressionType(typeof(double3x4), 75)]
[assembly: ExpressionType(typeof(double4), 76)]
[assembly: ExpressionType(typeof(double4x2), 77)]
[assembly: ExpressionType(typeof(double4x3), 78)]
[assembly: ExpressionType(typeof(double4x4), 79)]

[assembly: ExpressionType(typeof(half), 80)]
[assembly: ExpressionType(typeof(half2), 81)]
[assembly: ExpressionType(typeof(half3), 82)]
[assembly: ExpressionType(typeof(half4), 83)]
