name: Publish UPM Package

on:
  push:
    branches:
      - master

jobs:
  upm-release-essential:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: quabug/create-upm-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upm_package_path: Packages/essential
        upm_tag_prefix: essential/v
  upm-release-builder-component:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: quabug/create-upm-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upm_package_path: Packages/builder.component
        upm_tag_prefix: builder.component/v
  upm-release-debug-component-viewer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: quabug/create-upm-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upm_package_path: Packages/debug.component-viewer
        upm_tag_prefix: debug.component-viewer/v
  upm-release-variable-scriptable-object:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: quabug/create-upm-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upm_package_path: Packages/variable.scriptable-object
        upm_tag_prefix: variable.scriptable-object/v
  upm-release-samples:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: quabug/create-upm-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upm_package_path: Packages/samples
        upm_tag_prefix: samples/v
  upm-release-builder-visual:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: quabug/create-upm-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upm_package_path: Packages/builder.visual
        upm_tag_prefix: builder.visual/v
